### ISSUE TITLE
Implementare una nuova MainActivity (attività di lancio)

### ISSUE THREAD

**Issue by FedericoCalandra** [Enactus-Trieste/android-app-borghi#1]
Attualmente l'app si avvia dalla MainActivity (una sorta di menù iniziale dal quale si può navigare tra le varie activity con dei bottoni).

Per migliorare la user experience va creata una nuova activity principale (e.g. MainMapsActivity) che apra direttamente la mappa con le attività. Impostatarla come activity di lancio dal manifest.

**Comment by peiva-git** [comment]
Take a look [here](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomNavigation.md)
